export const GET_RESTAURANTS_REQUEST = "GET_RESTAURANTS_REQUEST";
export const GET_RESTAURANTS_SUCCESS = "GET_RESTAURANTS_SUCCESS";
export const GET_RESTAURANTS_FAILURE = "GET_RESTAURANTS_FAILURE";

export const FILTER_RESTAURANTS_REQUEST = "FILTER_RESTAURANTS_REQUEST";
export const FILTER_RESTAURANTS_SUCCESS = "FILTER_RESTAURANTS_SUCCESS";
export const FILTER_RESTAURANTS_FAILURE = "FILTER_RESTAURANTS_FAILURE";
